### ISSUE TITLE
Grab display name

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/registry-harvester#78]
To support getting the preferred name into Symphony user records, grab the display name from the registry data instead of the registered name.

**Comment by shelleydoljack** [comment]
Running on morison has not created any issues. Waiting for confirmation from @saseestone that we want to put this into production. We need to figure out how we want to re-harvest the users that have updated their display name.

**Comment by saseestone** [comment]
Let's go ahead and put it in production going forward.  You can start any day, but do let me know when you do, so that I can alert Privileges and other Operations Managers to the change.

Agreed that we still need to figure out how to re-harvest the users that have updated their display name.  I never heard from Helen.  Perhaps we need to put in a helpsu?
